#!/usr/bin/env python

import time
import subprocess
import getpass
import hashlib
import sys
import base64

def writeClipboard(content):
    process = subprocess.Popen('pbcopy', env={'LANG': 'en_US.UTF-8'}, stdin=subprocess.PIPE)
    process.communicate(content.encode('utf-8'))

def main():
    if len(sys.argv) != 2:
        print "error, usage: {} <domain>".format(sys.argv[0])
        sys.exit(1)
    domain = sys.argv[1]

    master  = getpass.getpass()
    confirm = getpass.getpass()
    if master != confirm:
        print "bad match"
        sys.exit(1)

    try:
        password = base64.b64encode(hashlib.pbkdf2_hmac('sha256', master, domain, 1000000))[:15]
        writeClipboard(password)
        print "password ready"
        time.sleep(7)
    finally: # if user sends a KeyboardInterrupt, wipe the clipboard before exiting
        writeClipboard("null")
        print "wiped"


main()
