#!/bin/bash

DICT=/usr/share/dict/words

dictsize() {
    wc -l < $DICT
}

randword () {
    int=$(od -A n -t u -N 4 /dev/urandom)
    index=$((int % $(dictsize)))
    awk -v lineno="$index" 'lineno==NR{print;exit}' $DICT
}

COUNT=${1:-8}
if [[ $COUNT -lt 1 ]]
then
    printf "error, <count> should be at least 1"
fi

printf "Creating password with %.2f bits of entropy...\n" "$(echo "$COUNT*l($(dictsize))/l(2)" | bc -l)"
for ((i=0;i<COUNT;i++)); do
    printf "%s " "$(randword)"
done

printf "\n"
